language: rust
sudo: false

rust:
  - nightly

os:
  - linux

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - FEATURES="unstable"
    - FEATURES="unstable memfd"

script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
